### ISSUE TITLE
Get Nears Coordinate from a Cluster

### ISSUE THREAD

**Issue by andri471** [bdelespierre/php-kmeans#2]
How i can Get Nears Point data of the Cluster , Example 

Cluster 0 [50,64]: 5 points
[81,95]       <----------------------- this ?
[43,95] 
[17,65] 
[49,93] 
[30,62] 

How I get Nears Point of this cluster 0 from the centroid ?

**Comment by bdelespierre** [comment]
Points are attached to the cluster using a SplObjectStorage object. Since this structure doesn't allow direct access, you'll have to convert it into an array first:

``` PHP
$clusters = $space->solve(3);

$firstClusterPoints = [];
foreach ($clusters[0] as $point)
  $firstClusterPoints[] = $point;

printf("The first point of the first cluster is [%d,%d]", $firstClusterPoints[0][0], $firstClusterPoints[0][1]);
printf("The second point of the first cluster is [%d,%d]", $firstClusterPoints[1][0], $firstClusterPoints[1][1]);
// etc.
```

**Comment by andri471** [comment]
i have longitude and latitude data. i want to cluster it using k-means methold. 
i cluster it into 3cluster. but i have one cluster.

example : 

cluster 0 : -5.132143, 119.407386 . 12 member
-5.130455, 119.408202
-5.130797, 119.407998
-5.131780, 119.407536
-5.132143, 119.407386
-5.132704, 119.407102
-5.132624, 119.407153
-5.132544, 119.407180
-5.132755, 119.407048
-5.132779, 119.407233
-5.132784, 119.407362
-5.132819, 119.407432
-5.132846, 119.407948

cluster 1 : -5.132846, 119.407948 . 0 member.
cluster 2 : -5.132842, 119.407538 . 0 member.

i dont use k means ++ to solve it. can you help me?

**Comment by andri471** [comment]
i has been added 100 data but. the output has one cluster too

**Comment by bdelespierre** [comment]
Sure, can you provide the original dataset so I can give it a try and see what's wrong ?

**Comment by bdelespierre** [comment]
The really strange thing in your result is all the points looks the same... I think there's an underneath problem. Anyway I'll need to have a look at your code to help.

**Comment by andri471** [comment]
this is a area 1
-5.130455, 119.408202
-5.130797, 119.407998
-5.131780, 119.407536
-5.132143, 119.407386
-5.132704, 119.407102
-5.132624, 119.407153
-5.132544, 119.407180
-5.132755, 119.407048
-5.132779, 119.407233
-5.132784, 119.407362
-5.132819, 119.407432
-5.132846, 119.407948
this is a area 2
-5.131801, 119.405959
-5.131449, 119.406185
-5.131823, 119.405584
-5.132079, 119.405627
-5.131972, 119.405831
-5.132122, 119.406174
-5.131716, 119.406045
-5.131075, 119.406528
-5.132197, 119.406292
-5.132624, 119.406818
-5.132368, 119.406506
this is a area 3
-5.132913, 119.409317
-5.132934, 119.409575
-5.132785, 119.409854
-5.132870, 119.410111
-5.132977, 119.410315
-5.133276, 119.410605
-5.132870, 119.410605
-5.132945, 119.410819
-5.132998, 119.411088
-5.132592, 119.411292
-5.133030, 119.411656
-5.132977, 119.411839
-5.133009, 119.411495
-5.131887, 119.411860
-5.132122, 119.411903
-5.132464, 119.411849
-5.132710, 119.411828
-5.132956, 119.411860
-5.132966, 119.412257
-5.133020, 119.412053
-5.132763, 119.412676
-5.133052, 119.412643
-5.133020, 119.412997
-5.132998, 119.413255
-5.132656, 119.413512
-5.132956, 119.413802
-5.133426, 119.413684
this is a area 4
-5.132956, 119.414113
-5.132838, 119.414392
-5.133180, 119.414725
-5.132688, 119.414972
-5.132560, 119.415336
-5.132453, 119.415572
-5.132571, 119.415057
-5.132357, 119.416066
-5.131823, 119.417643
-5.131011, 119.420368
-5.131299, 119.419360
-5.131695, 119.419274
-5.132208, 119.419306
-5.131994, 119.417074
this is a area 5
-5.134772, 119.422718
-5.134836, 119.423254
-5.134879, 119.424112
-5.134793, 119.421280
-5.134858, 119.420529
-5.135135, 119.422117
-5.133875, 119.421817
-5.134537, 119.422031
-5.134815, 119.423748
-5.134879, 119.424949
-5.135712, 119.422289
-5.134815, 119.424992
-5.135007, 119.426001
-5.134986, 119.426881
-5.135071, 119.427932
-5.134494, 119.427825
-5.135071, 119.427524
-5.135541, 119.426773
-5.133041, 119.427267
-5.133490, 119.427481
-5.135114, 119.428232

this is a area 6
-5.166273, 119.411034
-5.166444, 119.411452
-5.166540, 119.411774
-5.166262, 119.412032
-5.164897, 119.412362
-5.165261, 119.412276
-5.168028, 119.411546
-5.167387, 119.411729
-5.166554, 119.411697
-5.166746, 119.412212
-5.166789, 119.411911
-5.168712, 119.411375
-5.166222, 119.412061
-5.166833, 119.412524
-5.165908, 119.410233
-5.164861, 119.413023
-5.164541, 119.412191
-5.164530, 119.412465
-5.164599, 119.412438
-5.164808, 119.412948
-5.164546, 119.412277

**Comment by andri471** [comment]
this is my code demo.php http://codepaste.net/rk84mf

output http://codepaste.net/a9hta9  (20 cluster)

http://codepaste.net/etj563  (10 cluster)

can you convert (spatial data)  to use k means ?
sorry my bad english

**Comment by bdelespierre** [comment]
The problem with the provided number is that the euclidian distance between points is ommited due to float precision being too low to compute a good result. A quick workaround is to multiply every number by 1000000 to get rid of the precision problem (and divide them back by 10000 to get the proper coordinates)

**Comment by andri471** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9648608/8209693/9bcabdfc-1538-11e5-88e1-57a62d774447.png)

**Comment by bdelespierre** [comment]
working example:

``` PHP
<?php

// include the library
require_once "src/KMeans/Space.php";
require_once "src/KMeans/Point.php";
require_once "src/KMeans/Cluster.php";


$points= [
    [-5.166273, 119.411034],
    [-5.166444, 119.411452],
    [-5.166540, 119.411774],
    [-5.166262, 119.412032],
        ....
];

// create a 2-dimentions space
$space = new KMeans\Space(2);

define("PRECISION", 1000000);

// add points to space
foreach ($points as $coordinates) {
    $coordinates[0] *= PRECISION;
    $coordinates[1] *= PRECISION;
    $space->addPoint($coordinates);
}

// cluster these 50 points in 3 clusters
$clusters = $space->solve(3);

// display the cluster centers and attached points
foreach ($clusters as $i => $cluster)
    printf("Cluster %s [%f,%f]: %d points\n", $i, $cluster[0] / PRECISION, $cluster[1] / PRECISION, count($cluster));
```

Result:

```
Cluster 0 [-5.132526,119.410325]: 59 points
Cluster 1 [-5.166035,119.411979]: 21 points
Cluster 2 [-5.134145,119.423681]: 26 points
```

**Comment by andri471** [comment]
thanks for your help.
one problem, when i save it into db, value of the cluster[0] and [1] is -99.99999999 999.999999 ? 
when use the precision

**Comment by bdelespierre** [comment]
This is a bit out of scope from the k-mean project itself but let us see the code.

**Comment by andri471** [comment]
sorry about it. this my code http://codepaste.net/8y8t5s

![untitled](https://cloud.githubusercontent.com/assets/9648608/8210502/89dce5d0-153c-11e5-9d2c-3a911075b492.png)
the field is decimal 10,8 and 11,8 for longitude

before added the precision
![untitled](https://cloud.githubusercontent.com/assets/9648608/8210579/e8405fc6-153c-11e5-86da-593fabd47776.png)

**Comment by bdelespierre** [comment]
mmh. In any event you should round the precision using the [PHP round function](http://php.net/manual/fr/function.round.php) so you'll always have 8 or less decimals.

**Comment by andri471** [comment]
can you give me the example to implement it?

**Comment by bdelespierre** [comment]
http://php.net/manual/en/function.round.php#refsect1-function.round-examples

**Comment by andri471** [comment]
Thank you. To calculate the radius of each cluster based member farthest using the haversine formula.
To find the far member in centroid can use SplObjectStorage object ?

have you a alternative function to find fathest member (points) in each cluster ?

i want to add it to the Havesine formula

$latitude1, $longitude1, is the centorid [ i ]  and  $latitude2, $longitude2 is member farthest

this is the formula
echo (getDistance(-5.124721,119.418269,-5.124936,119.418293));

function getDistance($latitude1, $longitude1, $latitude2, $longitude2) {  
    $earth_radius = 6372800;  //meters

```
$dLat = deg2rad($latitude2 - $latitude1);  
$dLon = deg2rad($longitude2 - $longitude1);  

$a = sin($dLat/2) * sin($dLat/2) + cos(deg2rad($latitude1)) * cos(deg2rad($latitude2)) * sin($dLon/2) * sin($dLon/2);  
$c = 2 * asin(sqrt($a));  
$d = $earth_radius * $c;  

return $d;  
```

}

**Comment by bdelespierre** [comment]
Haversine formula is actualy a good idea. I'll have a look at it later and see if I can come up with an implementation. Stay tuned.

**Comment by andri471** [comment]
Sorry, please give me solution to find fathest member (points) in each cluster ?

**Comment by bdelespierre** [comment]
The answer is here: https://github.com/bdelespierre/php-kmeans/blob/master/src/KMeans/Point.php#L52

**Comment by andri471** [comment]
How to call it to demo.php ?  (Example Please to show coordinate)

**Comment by andri471** [comment]
Fatal error: Call to a member function getDistanceWith() on a non-object in D:\XAMPP\htdocs\php-kmeans-masters\demo_2.php on line 196
