### ISSUE TITLE
Is there a way to adapt the algorithm to use weighted centroid formula?

### ISSUE THREAD

**Issue by bdelespierre** [bdelespierre/php-kmeans#25]
One big problem with k-mean is the number of loops it does. But when the points are "close" to each other, why no group them together as a local cluster represented by a single weighted point? Would it make sense?

We could calculate for each point the shortest distance to another point. Then use the mean of these distances to determine which points are really "close" to each other by a user-specified factor. Then create a new point at the centroid of the selected points, giving it a weight equal to the number of points it represents. 

That could help lower the number of point-to-cluster-centroid distance computations, wouldn't it?

**Comment by battlecook** [comment]
I think the idea is good.
But I think there are some problems.
First, if "close" points are widely distributed, it may not be clear how to group some.
Second, the higher the dimensionality, the higher the probability that the points will be farther apart. 
Then putting a lot of points without weighting can be much more accurate for grouping clusters than weighting them.
I think it's a meaningful idea if implemented elaborately. But it seems like a pretty difficult challenge.

**Comment by bdelespierre** [comment]
I trust your judgment on this :+1:
