### ISSUE TITLE
Why do you need getData, setData($data) in Point Interface in v3?

### ISSUE THREAD

**Issue by battlecook** [bdelespierre/php-kmeans#26]
It seems clear that in PointInterface there are functions that deal with coordinates and space.

I confirmed that there are functions getData and setData to handle data. 

Can you explain what data means (or intention)?

**Comment by bdelespierre** [comment]
More often than not when you're clustering, you're doing it with vectorized representation of something else. Being able to recover the actual data from a point (its vector representation) is therefore quite helpful.

For instance, let's say I want N clusters of the geo position of my users. After I've done my clustering, I should be able to inspect a cluster like this:
```php
list($x, $y) = $cluster->getCentroid()->getCoordinates();
foreach ($cluster->getPoints() as $point) {
    echo "User {$point->getData()->getName()} belongs to cluster [{$x},{$y}]\n";
}
```

To do so, we need a way to "attach" arbitrary data to points. In v2 it was done using the array notation (which was quite confusing) `$space[$point] = $data`. The v3 target API looks like this (following the same example as before):

```php
$space = new Space(2); // 2d

foreach ($users as $user) {
    $point = new Point($space, [$user->getLatitude(), $user->getLongitude()]);
    $point->setData($user);
    array_push($points, $point);
}

$clusters = Algorithms\Kmeans::clusterize($points);
```

**Comment by battlecook** [comment]
I understand. thank you for explaining.

**Comment by bdelespierre** [comment]
My pleasure.
