### ISSUE TITLE
Packagist Release

### ISSUE THREAD

**Issue by Radiergummi** [bdelespierre/php-kmeans#36]
The current packagist release seems to be out of date? It is based on [tag 2.1.1](https://github.com/bdelespierre/php-kmeans/tree/v2.1.1), and seems to differ from the master branch. Would it be possible to update the release?

**Comment by bdelespierre** [comment]
Indeed. I pushed the v2.2.0 tag and it's now available on packagist. Thanks @Radiergummi 

Enjoy

**Comment by Radiergummi** [comment]
Perfect, thank you!
