### ISSUE TITLE
PHP 5.3 Compatibility

### ISSUE THREAD

**Issue by roncemer** [bdelespierre/php-kmeans#4]
Unbelievably, Amazon Linux, CentOS and RHEL still use PHP 5.3.  There are a few changes which are needed to support these platforms, which are still very prevalent.

Cluster.php, line 47.  Change this:
              $points = [];
to this:
              $points = array();

Cluster.php, lines 51-54.  Change this:
              return [
                      'centroid' => parent::toArray(),
                      'points'   => $points,
              ];
to this:
              return array(
                      'centroid' => parent::toArray(),
                      'points'   => $points,
              );

Point.php, lines 46-49.  Change this:
              return [
                      'coordinates' => $this->coordinates,
                      'data' => isset($this->space[$this]) ? $this->space[$this] : null,
              ];
to this:
              return array(
                      'coordinates' => $this->coordinates,
                      'data' => isset($this->space[$this]) ? $this->space[$this] : null,
              );

Space.php, line 53.  Change this:
              $points = [];
to this:
              $points = array();

Space.php, line 57.  Change this:
              return ['points' => $points];
to this:
              return array('points' => $points);

Space.php, line 101.  Change this:

Thanks!
Ron Cemer

**Comment by bdelespierre** [comment]
If you want these changes done, you should create a pull-request and I'll consider merging them :)

Besides, I don't see the point of supporting an [heavilly outdated version of PHP](http://php.net/supported-versions.php) anymore.

**Comment by roncemer** [comment]
I would agree, except that the most popular server OS in the world, CentOS, is still stuck in the dark ages with regard to PHP.  Fortunately, Ubuntu Server is rapidly gaining market share, and may have surpassed CentOS by now.

I'll go ahead and put this together for you.

Also, thanks for writing this package.  It works well!

**Comment by bdelespierre** [comment]
No problem. Your contribution is appreciated :+1:
