### ISSUE TITLE
Attaching an ID to each point

### ISSUE THREAD

**Issue by TheCrowned** [bdelespierre/php-kmeans#6]
Hi there,
is there any way to attach an ID to each point, to be able to tell which is which later? The ID shouldn't be used as a cluster variable, of course. Thanks!

**Comment by RyanfCooper** [comment]
This would be really nice!

**Comment by TheCrowned** [comment]
@bdelespierre any way this could make it in the project? Or if you are too busy, could you just give me directions on how to implement this?

**Comment by TheCrowned** [comment]
I've actually found a way to do what I need: attaching data to a point when adding it like this:

`$space->addPoint( $coordinates, array( 'ID' => $item_id ) );`

and then retrieving it all (coordinates + data) like this:

`var_dump( $point->toArray() );`

**Comment by kulcua** [comment]
Thank you, save my life.
